# Generated by Django 4.2.5 on 2024-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='blog/image/%y/%m/%d'),
        ),
    ]
