# Generated by Django 4.2.5 on 2024-01-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_maincontent_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='content/main_images/%y/%m/%d'),
        ),
    ]
