# Generated by Django 4.2.5 on 2024-01-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_maincontent_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='comment/images/%Y/%m/%d'),
        ),
    ]
